export const SORT_OPTIONS = [
  { value: "popularity.desc", text: "Popularity Descending" },
  { value: "popularity.asc", text: "Popularity Ascending" },
  { value: "vote_average.desc", text: "Rating Descending" },
  { value: "vote_average.asc", text: "Rating Ascending" },
  { value: "primary_release_date.desc", text: "Release Date Descending" },
  { value: "primary_release_date.asc", text: "Release Date Ascending" },
  { value: "title.asc", text: "Title (A-Z)" },
  { value: "title.desc", text: "Title (Z-A)" },
]

export const FILTER_CATS = [
  { value: "28", text: "Action" },
  { value: "12", text: "Adventure" },
  { value: "16", text: "Animation" },
  { value: "35", text: "Comedy" },
  { value: "80", text: "Crime" },
  { value: "99", text: "Documentary" },
  { value: "18", text: "Drama" },
  { value: "10751", text: "Family" },
  { value: "14", text: "Fantasy" },
  { value: "36", text: "History" },
  { value: "27", text: "Horror" },
  { value: "10402", text: "Music" },
  { value: "9648", text: "Mystery" },
  { value: "10749", text: "Romance" },
  { value: "878", text: "Science Fiction" },
  { value: "10770", text: "TV Movie" },
  { value: "53", text: "Thriller" },
  { value: "10752", text: "War" },
  { value: "37", text: "Western" },
]